### PR TITLE
Feature/detector gpt

### PR DESCRIPTION
**Pull request by chrstrom**
Wanted to test ChatGPTs ability to interpret the interface I wrote and asked it to make DBSCAN..... it did!

Need to change the tuning parameters, but other than that it is good to go!

### CODE REVIEW

**Comment by chrstrom** [comment]
Note to @vortexntnu/perception: If you also wish to learn to do this yourself, don't merge this right away 😸

**Comment by Bruglen** [comment]
LGTM

**Comment by chrstrom** [comment]
@Bruglen Sure you don't want a PR review from a few of the lidar ppl? There are at least a few things I can come up with from the top of my head that isn't 100%, like docstrings in the header files and READMEs/vortex wiki pages describing the theory behind the detectors.

I also think it could be beneficial to set up dynamic reconfigure on the ROS side of the detector, in order to do live tuning. This would also require a change in the interface and, as a consequence, the implemented detector.

**Comment by chrstrom** [comment]
Also I have not actually verified that anything other than the euclidean clustering algorithm actually does what the algorithms describe, so youd probably want to take a look at that !!!

**Pull request merged**
